const colors = {
  light: {
    text: '#121212',
    tint: '#e6002d',
    background: '#ffffff',
    foreground: '#121212',
    card: '#ffffff',
    cardForeground: '#121212',
    primary: '#e6002d',
    primaryForeground: '#ffffff',
    secondary: '#f1f1f1',
    secondaryForeground: '#191919',
    muted: '#f7f7f7',
    mutedForeground: '#6b6b6b',
    accent: '#fce6eb',
    accentForeground: '#9d1630',
    destructive: '#b42318',
    destructiveForeground: '#ffffff',
    border: '#e5e5e5',
    input: '#d0d0d0',
    metalDark: '#69737d',
    metalLight: '#f7fafc',
    metalMid: '#adb7c0',
    metalHighlight: '#ffffff',
  },
  dark: {
    text: '#ffffff',
    tint: '#e6002d',
    background: '#ffffff',
    foreground: '#121212',
    card: '#ffffff',
    cardForeground: '#121212',
    primary: '#e6002d',
    primaryForeground: '#ffffff',
    secondary: '#f1f1f1',
    secondaryForeground: '#191919',
    muted: '#f7f7f7',
    mutedForeground: '#6b6b6b',
    accent: '#fce6eb',
    accentForeground: '#9d1630',
    destructive: '#b42318',
    destructiveForeground: '#ffffff',
    border: '#e5e5e5',
    input: '#d0d0d0',
    metalDark: '#69737d',
    metalLight: '#f7fafc',
    metalMid: '#adb7c0',
    metalHighlight: '#ffffff',
  },
  radius: 8,
};

export default colors;